---
name: iconeval
channels:
  - conda-forge
  - nodefaults

dependencies:
  - fire
  - loguru
  - prov
  - python>=3.12
  - python-swiftclient
  - pyyaml
  - requests

  # develop
  - pre-commit
  - py-markdown-table
  - pytest
  - pytest-cov
  - pytest-mock
