---
name: Update Coverage Badge

permissions:
  contents: write

on:
  push:
    branches: [main]

# Required shell entrypoint to have properly configured bash shell
defaults:
  run:
    shell: bash -l {0}

jobs:
  update_badge:
    runs-on: ubuntu-latest
    name: Update Coverage Badge
    steps:
      - name: Set name of target branch
        run: |
          export TARGET_BRANCH=update_coverage_badge_$(date +%s)
          echo "TARGET_BRANCH=${TARGET_BRANCH}" >> ${GITHUB_ENV}
          echo "Target branch: ${TARGET_BRANCH}"
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: true  # necessary for git-auto-commit-action
      - name: Setup Conda environment
        uses: conda-incubator/setup-miniconda@fc2d68f6413eb2d87b895e92f8584b5b94a10167 # v3.3.0
        with:
          activate-environment: iconeval
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          miniforge-version: latest
          use-mamba: true
      - name: Install ICONEval
        run: pip install --no-deps -e .[develop]
      - name: Run tests
        run: |
          pytest -n 2 --junitxml=pytest.xml --cov-report=xml:coverage.xml --cov-report=term-missing --cov=iconeval tests/
      - name: Comment coverage
        id: coverage
        uses: MishaKav/pytest-coverage-comment@287292879eaaff04116f36d3eb1a670f6e5df1a4 # v1.7.1
        with:
          coverage-path-prefix: iconeval/
          hide-comment: true
          junitxml-path: ./pytest.xml
          pytest-xml-coverage-path: ./coverage.xml
      - name: Update README
        run: |
          sed -i "/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/c\<!-- Pytest Coverage Comment:Begin -->\n${STEPS_COVERAGE_OUTPUTS_COVERAGE_HTML}\n<!-- Pytest Coverage Comment:End -->" ./README.md
        env:
          STEPS_COVERAGE_OUTPUTS_COVERAGE_HTML: ${{ steps.coverage.outputs.coverageHtml }}
      - name: Detect changes
        run: |
          export GIT_DIFF=$(git diff --stat | head -n 1)
          echo "GIT_DIFF=${GIT_DIFF}" >> ${GITHUB_ENV}
          if [ "${GIT_DIFF}" == '' ]; then
            echo "No changes detected"
          else
            echo "Changes detected"
          fi
      - name: Commit changes
        if: ${{ env.GIT_DIFF != '' }}
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          branch: ${{ env.TARGET_BRANCH }}
          commit_message: Update coverage badge
          create_branch: true
          file_pattern: README.md
