---
name: Update Coverage Badge

permissions:
  contents: write

on:
  push:
    branches: [main]

# Required shell entrypoint to have properly configured bash shell
defaults:
  run:
    shell: bash -l {0}

jobs:
  update_badge:
    runs-on: ubuntu-latest
    name: Update Coverage Badge
    steps:
      - name: Set name of target branch
        run: |
          export CURRENT_DATE=${{ github.event.repository.updated_at}} | sed 's/:/./g'
          echo "TARGET_BRANCH=update_coverage_badge$CURRENT_DATE" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: true  # necessary for git-auto-commit-action
      - name: Setup Conda environment
        uses: conda-incubator/setup-miniconda@fc2d68f6413eb2d87b895e92f8584b5b94a10167 # v3.3.0
        with:
          activate-environment: iconeval
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          miniforge-version: latest
          use-mamba: true
      - name: Install ICONEval
        run: pip install --no-deps -e .[develop]
      - name: Run tests
        run: |
          pytest --cov-report=term-missing --junitxml=pytest.xml --cov-report=xml:coverage.xml --cov=iconeval tests/
      - name: Comment coverage
        uses: MishaKav/pytest-coverage-comment@26f986d2599c288bb62f623d29c2da98609e9cd4 # v1.6.0
        with:
          pytest-xml-coverage-path: ./coverage.xml
          junitxml-path: ./pytest.xml
          hide-comment: true
      - name: Update README
        run: |
          sed -i "/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/c\<!-- Pytest Coverage Comment:Begin -->\n${STEPS_COVERAGE_OUTPUTS_COVERAGE_HTML}\n<!-- Pytest Coverage Comment:End -->" ./README.md
        env:
          STEPS_COVERAGE_OUTPUTS_COVERAGE_HTML: ${{ steps.coverage.outputs.coverageHtml }}
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          branch: ${{ env.TARGET_BRANCH }}
          commit_message: Update coverage badge
          create_branch: true
          file_pattern: README.md
      - name: Create pull request
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: gh pr create -B main -H $TARGET_BRANCH --title 'Update coverage badge in README'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
